=== HXTgithub/xml-work/第10组xml/酒店信息管理系统/App_Data/client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="clientname" type="xs:string"/>
	<xs:element name="clientroom" type="xs:string"/>
	<xs:element name="clientphone" type="xs:string"/>
	<xs:element name="roomdate" type="xs:date"/>
	<xs:element name="roomtime" type="xs:int"/>
	<xs:element name="client" type="clienttype"/>
	<xs:complexType name="clienttype">
		<xs:sequence>
			<xs:element ref="clientname"/>
			<xs:element ref="clientroom"/>
			<xs:element ref="clientphone"/>
			<xs:element ref="roomdate"/>
			<xs:element ref="roomtime"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="clients" type="clientstype"/>
	<xs:complexType name="clientstype">
		<xs:sequence>
			<xs:element ref="client" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== HXTgithub/xml-work/第10组xml/酒店信息管理系统/App_Data/client.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/13739/Desktop/hotel/App_Data/client.xsd">
  <client>
    <clientname>1373948524</clientname>
    <clientroom>101</clientroom>
    <clientphone>18133336666</clientphone>
    <roomdate>2024-12-18</roomdate>
    <roomtime>4</roomtime>
  </client>
  <client>
    <clientname>1373948524</clientname>
    <clientroom>201</clientroom>
    <clientphone>18143990263</clientphone>
    <roomdate>2024-12-18</roomdate>
    <roomtime>3</roomtime>
  </client>
  <client>
    <clientname>user4</clientname>
    <clientroom>401</clientroom>
    <clientphone>18511112222</clientphone>
    <roomdate>2024-12-23</roomdate>
    <roomtime>4</roomtime>
  </client>
  <client>
    <clientname>user4</clientname>
    <clientroom>401</clientroom>
    <clientphone>18536524865</clientphone>
    <roomdate>2024-12-20</roomdate>
    <roomtime>5</roomtime>
  </client>
</clients>
