=== HXTgithub/xml-work/第10组xml/酒店信息管理系统/App_Data/manage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="managename" type="managenametype"/>
	<xs:simpleType name="managenametype">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9]{3,30}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="managemima" type="managemimatype"/>
	<xs:simpleType name="managemimatype">
		<xs:restriction base="xs:string">
			<xs:minLength value="6"/>
			<xs:pattern value="[A-Za-z0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="managesex" type="msextype"/>
	<xs:simpleType name="msextype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="男"/>
			<xs:enumeration value="女"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="managephone" type="xs:string"/>
	<xs:element name="manage" type="managetype"/>
	<xs:complexType name="managetype">
	<xs:sequence>
	    <xs:element ref="managename"/>
	    <xs:element ref="managemima"/>
	    <xs:element ref="managesex"/>
	    <xs:element ref="managephone"/>
	</xs:sequence>
	</xs:complexType>
	<xs:element name="manages" type="managestype"/>
	<xs:complexType name="managestype">
	<xs:sequence>
	    <xs:element ref="manage" maxOccurs="unbounded"/>
	</xs:sequence>
	</xs:complexType>
</xs:schema>

=== HXTgithub/xml-work/第10组xml/酒店信息管理系统/App_Data/manage.xml
<?xml version="1.0" encoding="UTF-8"?>
<manages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/13739/Desktop/hotel/App_Data/manage.xsd">
  <manage>
    <managename>1373948524</managename>
    <managemima>114514</managemima>
    <managesex>男</managesex>
    <managephone>18143990263</managephone>
  </manage>
  <manage>
    <managename>123456</managename>
    <managemima>123456</managemima>
    <managesex>男</managesex>
    <managephone>18143990263</managephone>
  </manage>
  <manage>
    <managename>LXP666</managename>
    <managemima>114514</managemima>
    <managesex>男</managesex>
    <managephone>12345678912</managephone>
  </manage>
  <manage>
    <managename>admin</managename>
    <managemima>112233</managemima>
    <managesex>男</managesex>
    <managephone>18536852658</managephone>
  </manage>
  <manage>
    <managename>admin1</managename>
    <managemima>123456</managemima>
    <managesex>男</managesex>
    <managephone>18536852658</managephone>
  </manage>
  <manage>
    <managename>admin3</managename>
    <managemima>112233</managemima>
    <managesex>男</managesex>
    <managephone>18536852658</managephone>
  </manage>
</manages>
