=== HXTgithub/xml-work/第10组xml/酒店信息管理系统/App_Data/rooms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:attribute name="roomid" type="xs:string"/>
	<xs:attribute name="roomtype" type="Roomtype"/>
	<xs:simpleType name="Roomtype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="大床房"/>
			<xs:enumeration value="双床房"/>
			<xs:enumeration value="情侣房"/>
			<xs:enumeration value="家庭房"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="sales" type="xs:string"/>
	<xs:element name="roomsize" type="xs:string"/>
	<xs:element name="people" type="xs:string"/>
	<xs:element name="bed" type="xs:string"/>
	<xs:element name="price" type="xs:string"/>
	<xs:element name="condition" type="conditype"/>
	<xs:simpleType name="conditype">
		<xs:restriction base="xs:string">
		    <xs:enumeration value="已预订"/>
		    <xs:enumeration value="未预订"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="photo" type="xs:string"/>
	<xs:element name="room">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="roomsize"/>
				<xs:element ref="bed"/>
				<xs:element ref="sales"/>
				<xs:element ref="people"/>
				<xs:element ref="price"/>
				<xs:element ref="condition"/>
				<xs:element ref="photo"/>
			</xs:sequence>
			<xs:attribute ref="roomid"/>
			<xs:attribute ref="roomtype"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="rooms">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="room" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="roomidunique">
			<xs:selector xpath="./room"/>
			<xs:field xpath="@roomid"/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== HXTgithub/xml-work/第10组xml/酒店信息管理系统/App_Data/rooms.xml
<?xml version="1.0" encoding="UTF-8"?>
<rooms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/13739/Desktop/hotel/App_Data/rooms.xsd">
  <room roomid="101" roomtype="双床房">
    <roomsize>30平方米</roomsize>
    <bed>1.2米大床</bed>
    <sales>800+</sales>
    <people>2人</people>
    <price>200</price>
    <condition>已预订</condition>
    <photo>~/photo/room1.png</photo>
  </room>
  <room roomid="201" roomtype="大床房">
    <roomsize>35平方米</roomsize>
    <bed>1.9米大床</bed>
    <sales>500+</sales>
    <people>1人</people>
    <price>350</price>
    <condition>已预订</condition>
    <photo>~/photo/room3.png</photo>
  </room>
  <room roomid="301" roomtype="亲子房">
    <roomsize>35平方米</roomsize>
    <bed>1.9米大床</bed>
    <sales>500+</sales>
    <people>3人</people>
    <price>400</price>
    <condition>已预订</condition>
    <photo>~/photo/room1.png</photo>
  </room>
  <room roomid="401" roomtype="超值房">
    <roomsize>20平方米</roomsize>
    <bed>1.9米大床</bed>
    <sales>500+</sales>
    <people>3人</people>
    <price>700</price>
    <condition>未预订</condition>
    <photo>~/photo/room1.png</photo>
  </room>
</rooms>
