=== HXTgithub/xml-work/第10组xml/酒店信息管理系统/App_Data/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="username" type="usernametype"/>
	<xs:simpleType name="usernametype">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9]{3,30}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="usermima" type="usermimatype"/>
	<xs:simpleType name="usermimatype">
		<xs:restriction base="xs:string">
			<xs:minLength value="6"/>
			<xs:pattern value="[A-Za-z0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="sex" type="sextype"/>
	<xs:simpleType name="sextype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="男"/>
			<xs:enumeration value="女"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="mibaoquestion" type="xs:string"/>
	<xs:element name="mibaoanser" type="xs:string"/>
	<xs:element name="tel" type="teltype"/>
	<xs:simpleType name="teltype">
		<xs:restriction base="xs:string">
			<xs:length value="11"/>
			<xs:pattern value="1[3-9][0-9]{9}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="email" type="emailtype"/>
	<xs:simpleType name="emailtype">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="birthdate" type="xs:date"/>
	<xs:element name="photo" type="xs:string"/>
	<xs:element name="user" type="usertype"/>
	<xs:complexType name="usertype">
		<xs:sequence>
			<xs:element ref="username"/>
			<xs:element ref="usermima"/>
			<xs:element ref="sex"/>
			<xs:element ref="mibaoquestion"/>
			<xs:element ref="mibaoanser"/>
			<xs:element ref="tel"/>
			<xs:element ref="email"/>
			<xs:element ref="birthdate"/>
			<xs:element ref="photo"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="users" type="userstype">
		<xs:unique name="usernameunique">
			<xs:selector xpath="./user"/>
			<xs:field xpath="@username"/>
		</xs:unique>
	</xs:element>
	<xs:complexType name="userstype">
		<xs:sequence>
			<xs:element ref="user" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== HXTgithub/xml-work/第10组xml/酒店信息管理系统/App_Data/userdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/13739/Desktop/web%20-%20%e5%89%af%e6%9c%ac/App_Data/user.xsd">
  <user>
    <username>1234</username>
    <usermima>12345678</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>123</mibaoanser>
    <tel>18143990263</tel>
    <email>1234@qq.com</email>
    <birthdate>2004-12-14</birthdate>
    <photo>~/photo/01.png</photo>
  </user>
  <user>
    <username>1373948524</username>
    <usermima>114514</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>拳刃</mibaoanser>
    <tel>18143990263</tel>
    <email>1373948524@qq.com</email>
    <birthdate>2004-12-14</birthdate>
    <photo>~/photo/屏幕截图_20221120_155314.png</photo>
  </user>
  <user>
    <username>66666</username>
    <usermima>123456</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>拳刃</mibaoanser>
    <tel>18143990263</tel>
    <email>138@qq.com</email>
    <birthdate>2004-12-05</birthdate>
    <photo>~/photo/屏幕截图_20221120_155314.png</photo>
  </user>
  <user>
    <username>789456</username>
    <usermima>123456</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>企鹅</mibaoanser>
    <tel>18143990263</tel>
    <email>184@qq.com</email>
    <birthdate>2004-12-18</birthdate>
    <photo>~/photo/屏幕截图_20221120_155314.png</photo>
  </user>
  <user>
    <username>147258</username>
    <usermima>123456</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>企鹅</mibaoanser>
    <tel>18143990263</tel>
    <email>182@qq.com</email>
    <birthdate>2005-12-01</birthdate>
    <photo>~/photo/屏幕截图_20221120_155314.png</photo>
  </user>
  <user>
    <username>LXP666</username>
    <usermima>114514</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>拳刃</mibaoanser>
    <tel>12345678912</tel>
    <email>135@qq.com</email>
    <birthdate>2005-12-09</birthdate>
    <photo>~/photo/屏幕截图_20221120_163758.png</photo>
  </user>
  <user>
    <username>user1</username>
    <usermima>112233</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>剑</mibaoanser>
    <tel>18536524865</tel>
    <email>123@qq.com</email>
    <birthdate>2024-12-13</birthdate>
    <photo>~/photo/屏幕截图 2022-10-03 221807.png</photo>
  </user>
  <user>
    <username>use2</username>
    <usermima>11223344</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>剑</mibaoanser>
    <tel>18536524865</tel>
    <email>123@qq.com</email>
    <birthdate>2024-12-14</birthdate>
    <photo>~/photo/屏幕截图 2022-10-03 221807.png</photo>
  </user>
  <user>
    <username>user2</username>
    <usermima>112233</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>剑</mibaoanser>
    <tel>18536524865</tel>
    <email>123@qq.com</email>
    <birthdate>2024-12-06</birthdate>
    <photo>~/photo/屏幕截图 2022-10-03 221807.png</photo>
  </user>
  <user>
    <username>user4</username>
    <usermima>112233</usermima>
    <sex>男</sex>
    <mibaoquestion>最喜欢的武器是什么</mibaoquestion>
    <mibaoanser>剑</mibaoanser>
    <tel>18536524865</tel>
    <email>123@qq.com</email>
    <birthdate>2024-12-03</birthdate>
    <photo>~/photo/示例.jpg</photo>
  </user>
</users>
